"""Initial migration for db_symptoms

Revision ID: 0a0613b31ff9
Revises: 8850f928edf3
Create Date: 2025-02-25 17:05:05.854410

"""


# revision identifiers, used by Alembic.
revision = '0a0613b31ff9'
down_revision = '8850f928edf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
