"""Migration for symptoms

Revision ID: 43de484ec9da
Revises: 0a0613b31ff9
Create Date: 2025-02-25 17:28:56.750621

"""


# revision identifiers, used by Alembic.
revision = '43de484ec9da'
down_revision = '0a0613b31ff9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
