"""Initial migration for db_symptoms

Revision ID: 729c64e0ea4a
Revises: 57ac8defe8c7
Create Date: 2025-02-25 08:03:40.334996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729c64e0ea4a'
down_revision = '57ac8defe8c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
