"""Remove FK from user_symptoms

Revision ID: 8205f63643ed
Revises: 43de484ec9da
Create Date: 2025-02-25 18:04:02.883695

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8205f63643ed'
down_revision = '43de484ec9da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_symptoms_id', table_name='symptoms')
    op.drop_index('ix_symptoms_name', table_name='symptoms')
    op.drop_table('symptoms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptoms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='symptoms_pkey')
    )
    op.create_index('ix_symptoms_name', 'symptoms', ['name'], unique=False)
    op.create_index('ix_symptoms_id', 'symptoms', ['id'], unique=False)
    op.drop_table('user_symptoms')
    # ### end Alembic commands ###
