"""Initial migration for db_symptoms

Revision ID: 8850f928edf3
Revises: 729c64e0ea4a
Create Date: 2025-02-25 08:10:27.001905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8850f928edf3'
down_revision = '729c64e0ea4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
