"""changed symptoms, diseases

Revision ID: bce5cb1d0a53
Revises: a14c8285b2b4
Create Date: 2025-04-21 08:05:39.653759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bce5cb1d0a53'
down_revision: Union[str, None] = 'a14c8285b2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_symptoms', sa.Column('disease_id', sa.Integer(), nullable=True))
    op.alter_column('user_symptoms', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'user_symptoms', 'diseases', ['disease_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_symptoms', type_='foreignkey')
    op.alter_column('user_symptoms', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('user_symptoms', 'disease_id')
    # ### end Alembic commands ###