services:
  symptosay:
    build: ./symptosay
    container_name: symptosay
    env_file: ./symptosay/.env
    depends_on:
      - user_service
    networks:
      - app_network

  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
