services:
  symptosay:
    build: ./symptosay
    container_name: symptosay
    env_file: ./.env
    depends_on:
      - user_service
    networks:
      - app_network

  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      user_service_db:
        condition: service_healthy
    env_file:
      - ./.env

  user_service_db:
    image: postgres:17-alpine3.20
    container_name: user_service_db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d users"]
      interval: 2s
      timeout: 3s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
