version: "3.9"

services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  database_service:
    build:
      context: ./database_service
      dockerfile: Dockerfile
    container_name: database_service
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8001:8001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
