[project]
name = "user-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "alembic>=1.14.1",
    "fastapi>=0.115.8",
    "sqlalchemy>=2.0.38",
    "uvicorn>=0.34.0",
]

