[tool.ruff.lint]
select = ["E", "F", "I", "S", "UP"]
extend-ignore = ["E203"]

[tool.ruff]
target-version = "py312"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
